In [2]:
import numpy
numpy.__version__

'1.16.2'

In [3]:
import numpy as np
np?

### Python的整型不仅仅是一个整型

> Python 3.4 中的一个整型实际上包括 4 个部分
- ob_refcnt 是一个引用计数，它帮助 Python 默默地处理内存的分配和回收。
- ob_type 将变量的类型编码。
- ob_size 指定接下来的数据成员的大小。
- ob_digit 包含我们希望 Python 变量表示的实际整型值。

- 而 Python 的整型其实是一个指针，指向包含这个 Python 对象所有信息的某个内 存位置，其中包括可以转换成整型的字节。由于 Python 的整型结构体里面还包含了大量额 外的信息，所以 Python 可以自由、动态地编码。但是，Python 类型中的这些额外信息也 会成为负担，在多个对象组合的结构体中尤其明显。

### Python的列表不仅仅是一个列表

> Python的列表中有很多元素，每一个元素都可以看做是一个对象，那么每个对象都有各自的信息，例如：引用计数、类型等，加入所有的数据类型都是相同的，那么很多相同的类型记录会显得很冗余，所以使用NumPy数组比Python列表要好。

### 用Python列表创建数组

In [6]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
np.array([1,2,'3',4])

array(['1', '2', '3', '4'], dtype='<U21')

> 需要注意不同于Python列表的是NumPy要求数组元素必须为同一种类型，传入的列表元素不同种类型会被转换。如果希望指定NumPy数组类型，可以指定。

In [10]:
np.array([1,2,'3',4],dtype = 'int')

array([1, 2, 3, 4])

In [11]:
np.array([range(i, i+2) for i in range(1, 3)])

array([[1, 2],
       [2, 3]])

> 传入多维的列表，会变为多维数组。

### 从头创建数组

In [13]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [18]:
np.full((3,5),1,dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
np.random.random((3,3))

array([[0.63998818, 0.65983829, 0.73809837],
       [0.39056431, 0.27368677, 0.53262692],
       [0.35879088, 0.63115795, 0.38619657]])

创建一个3*3，均值为0，方差为1，正态分布随机数组

In [27]:
np.random.normal(0,1,(3,3))

array([[-1.75869331, -1.03117361, -0.76946194],
       [ 0.29255505,  0.45816751,  2.38001321],
       [ 2.140834  , -1.76606977,  0.51925206]])

创建一个3*3，在[0,10)区间的随机整型数组

In [30]:
np.random.randint(0,10,(3,3))

array([[9, 2, 6],
       [0, 8, 7],
       [1, 1, 3]])

创建3*3的单位矩阵

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

创建一个由3个整型数组成的未初始化的数组,数组的值是内存空间中的任意值

In [35]:
np.empty(3)

array([1., 1., 1.])