### NumPy数组的属性

> 确定数组的大小、形状、存储大小、数据类型

In [1]:
import numpy as np
np.random.seed(0)  # 设置随机数种子

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [2]:
x1

array([5, 0, 3, 3, 7, 9])

In [3]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [4]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [5]:
print('x1,x2,x3数组的维度分别是{},{},{}'.format(x1.ndim,x2.ndim,x3.ndim))
print('x1,x2,x3数组每个维度的大小分别是{},{},{}'.format(x1.shape,x2.shape,x3.shape))
print('x1,x2,x3数组的总大小分别是{},{},{}'.format(x1.size,x2.size,x3.size))

x1,x2,x3数组的维度分别是1,2,3
x1,x2,x3数组每个维度的大小分别是(6,),(3, 4),(3, 4, 5)
x1,x2,x3数组的总大小分别是6,12,60


In [6]:
print(x1.dtype)

int64


### 数组索引

In [7]:
x1

array([5, 0, 3, 3, 7, 9])

In [8]:
x1[0]

5

In [9]:
x1[100]

IndexError: index 100 is out of bounds for axis 0 with size 6

In [ ]:
for i in x1:
    print(i)

In [ ]:
x2

In [ ]:
x2[0]

In [ ]:
x2[0][2]

In [ ]:
x2[0,2]  # 多维数组中可以使用一个中括号，里面分别写上索引。

In [ ]:
x2[-1][-1]

In [ ]:
x2[-1,-1]=8

In [ ]:
x2

In [ ]:
# 插入的数据会根据数组的类型进行调整
x2[-1,-1]=3.14

In [ ]:
x2.dtype

In [ ]:
x2[-1,-1]

### 数组切片

通过数组切片，获取子数组

一维子数组

In [ ]:
x1

In [ ]:
x1[::-1]

In [ ]:
x1[:5]  # 获取前五个元素

In [ ]:
x1[-5:]  # 获取后五个元素

多维子数组

In [ ]:
x2

In [ ]:
x2[:2,:3]

In [ ]:
x2[:,::2]  # 逗号前后分别表示 行 列

In [ ]:
x2[::-1,::-1]  # 实现逆序

获取数组的行和列

In [ ]:
# 获取第一行
x2[0,:]

In [ ]:
# 获取第一列
x2[:,0]

In [ ]:
# 回去行的时候为了语法简便可以直接获取
x2[2]

非副本视图的子数组

> 在获取到切片时，其实是获取的视图，而不是副本，也就是修改原数据，会随之变化。

In [ ]:
x1

In [ ]:
x1[2]

In [ ]:
x1[2]=6

In [ ]:
x1[2]

In [ ]:
x1

In [ ]:
xx=x1[1:4]

In [ ]:
xx

In [ ]:
x1[1]

In [ ]:
x1[1]=1

In [ ]:
x1

In [ ]:
xx

创建数组的副本

In [ ]:
x1

In [ ]:
xxx = x1.copy()

In [ ]:
xxx

In [ ]:
x1[0]=0

In [ ]:
x1

In [ ]:
xxx

### 数组的拼接和分裂

拼接

In [12]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
cdshi