### NumPy数组的属性

> 确定数组的大小、形状、存储大小、数据类型

In [23]:
import numpy as np
np.random.seed(0)  # 设置随机数种子

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [24]:
x1

array([5, 0, 3, 3, 7, 9])

In [25]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [26]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [32]:
print('x1,x2,x3数组的维度分别是{},{},{}'.format(x1.ndim,x2.ndim,x3.ndim))
print('x1,x2,x3数组每个维度的大小分别是{},{},{}'.format(x1.shape,x2.shape,x3.shape))
print('x1,x2,x3数组的总大小分别是{},{},{}'.format(x1.size,x2.size,x3.size))

x1,x2,x3数组的维度分别是1,2,3
x1,x2,x3数组每个维度的大小分别是(6,),(3, 4),(3, 4, 5)
x1,x2,x3数组的总大小分别是6,12,60


In [33]:
print(x1.dtype)

int64


### 数组索引

In [35]:
x1

array([5, 0, 3, 3, 7, 9])

In [37]:
x1[0]

5

In [38]:
x1[100]

IndexError: index 100 is out of bounds for axis 0 with size 6

In [39]:
for i in x1:
    print(i)

5
0
3
3
7
9


In [40]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [41]:
x2[0]

array([3, 5, 2, 4])

In [44]:
x2[0][2]

2

In [46]:
x2[0,2]  # 多维数组中可以使用一个中括号，里面分别写上索引。

2

In [43]:
x2[-1][-1]

7

In [47]:
x2[-1,-1]=8

In [48]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 8]])

In [52]:
# 插入的数据会根据数组的类型进行调整
x2[-1,-1]=3.14

In [55]:
dtype(x2)

NameError: name 'dtype' is not defined

In [51]:
x2[-1,-1]

3

### 数组切片

### 数组的变形

### 数组的拼接和分裂