In [12]:
import numpy as np

np.random.seed(0)
print(np.random.rand(2))
print(np.random.rand(2))

np.random.seed(1)
print(np.random.rand(2))
print(np.random.rand(2))

np.random.seed(0)
print(np.random.rand(2))
print(np.random.rand(2))

np.random.seed(1)
print(np.random.rand(2))
print(np.random.rand(2))

[0.5488135  0.71518937]
[0.60276338 0.54488318]
[0.417022   0.72032449]
[1.14374817e-04 3.02332573e-01]
[0.5488135  0.71518937]
[0.60276338 0.54488318]
[0.417022   0.72032449]
[1.14374817e-04 3.02332573e-01]


In [14]:
value = np.random.randint(1, 10, size=5)
print(value)

[3 5 6 3 5]


In [15]:
np.empty(value)

array([[[[[0.00000000e+000, 2.37851796e-314, 0.00000000e+000,
           2.37851796e-314, 2.37851805e-314],
          [2.37851819e-314, 2.37851825e-314, 2.37851830e-314,
           2.37851836e-314, 2.37851841e-314],
          [2.37851847e-314, 2.37851852e-314, 2.37851858e-314,
           2.37851880e-314, 2.37851869e-314]],

         [[2.37851875e-314, 2.37851863e-314, 2.37851897e-314,
           2.37851891e-314, 2.37851902e-314],
          [2.37851343e-314, 2.37851348e-314, 2.37851354e-314,
           2.37851359e-314, 2.37851365e-314],
          [2.37851370e-314, 2.37851376e-314, 2.37851381e-314,
           2.37851387e-314, 2.37857802e-314]],

         [[2.37857857e-314, 2.37857868e-314, 2.37857874e-314,
           2.37857879e-314, 2.37857885e-314],
          [2.37857890e-314, 2.37857896e-314, 2.37857901e-314,
           2.37857907e-314, 2.37857912e-314],
          [2.37857918e-314, 2.37857923e-314, 2.37857929e-314,
           2.37857935e-314, 2.37857940e-314]],

         [[2.37857946e

In [18]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [21]:
%timeit compute_reciprocals(values)

13.9 µs ± 265 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [22]:
v1 = np.random.randint(1,100,1000000)
%timeit compute_reciprocals(v1)

2.31 s ± 41.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [23]:
values

array([6, 1, 4, 4, 8])

In [24]:
print(compute_reciprocals(values))
print(1/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [25]:
%timeit (1/values) # 可以发现使用 / 比使用函数进行计算快很多

1.47 µs ± 27.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [26]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [28]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [29]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
np.arange(1,13).reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
x = np.arange(1,13).reshape((4,3))
x ** 2

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

通用函数有两种存在形式：一元通用函数和二元通用函数

使用Python的原生算数运算符就是使用通用函数

In [1]:
import numpy as np
x = np.array([-1,-2,0,1,2])
x

array([-1, -2,  0,  1,  2])

In [2]:
abs(x)

array([1, 2, 0, 1, 2])

In [3]:
x

array([-1, -2,  0,  1,  2])

In [4]:
np.absolute(x)

array([1, 2, 0, 1, 2])

In [5]:
x

array([-1, -2,  0,  1,  2])