In [1]:
import numpy as np
l = np.random.random(100)
l

array([0.87751323, 0.85172516, 0.79582857, 0.65200047, 0.77729355,
       0.01173251, 0.41665896, 0.48264754, 0.91448708, 0.67172286,
       0.26662212, 0.88079639, 0.29454728, 0.44878312, 0.72952115,
       0.98045849, 0.36163967, 0.71196109, 0.30337499, 0.34879575,
       0.2578723 , 0.92650867, 0.69252949, 0.0695754 , 0.67064541,
       0.38907091, 0.08905214, 0.70193148, 0.61473935, 0.66065687,
       0.07988451, 0.20141809, 0.63075829, 0.43279099, 0.83733794,
       0.75226259, 0.53051096, 0.59135761, 0.97741111, 0.92422888,
       0.95956589, 0.25980229, 0.51099821, 0.53019551, 0.89372406,
       0.88116957, 0.81514969, 0.08469764, 0.44938525, 0.14556312,
       0.80394467, 0.8886897 , 0.80835602, 0.16981828, 0.21483735,
       0.39723514, 0.4181911 , 0.87659854, 0.15964459, 0.2085072 ,
       0.50030331, 0.99148365, 0.8794069 , 0.85762117, 0.63880837,
       0.10796592, 0.78935663, 0.98518511, 0.22924855, 0.85032956,
       0.95513342, 0.95156651, 0.28245267, 0.88006896, 0.30329

In [2]:
%timeit sum(l)

11.1 µs ± 77.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [3]:
%timeit np.sum(l)

4.68 µs ± 88.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
np.min(l)

0.01173251316211843

In [5]:
np.max(l)

0.9933327773708532

In [6]:
M = np.random.random((3,4))
M

array([[0.03992389, 0.12305699, 0.78923031, 0.70671068],
       [0.51448978, 0.03570359, 0.48946937, 0.07161062],
       [0.60421335, 0.08902629, 0.24991496, 0.2120001 ]])

In [7]:
np.sum(M)

3.9253499209506706

In [8]:
np.sum(M,axis=0)  # 每一列的和

array([1.15862702, 0.24778687, 1.52861463, 0.9903214 ])

In [9]:
np.sum(M,axis=1)  # 每一行的和

array([1.65892186, 1.11127336, 1.1551547 ])