In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2])
b = np.array([5,5,5])

In [3]:
a + b

array([5, 6, 7])

对于同等维度的数组可以对对应的元素进行操作，那么广播允许标量和数组相加

In [4]:
a + 5

array([5, 6, 7])

In [5]:
c = np.array([1,2])

In [6]:
a + c

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [7]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
a

array([0, 1, 2])

In [9]:
a + M

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [10]:
M + 5

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [11]:
a = np.arange(3)
a

array([0, 1, 2])

In [15]:
b = np.arange(3)[:,np.newaxis]  # 实现x y轴互换
b

array([[0],
       [1],
       [2]])

In [16]:
a + b  # 两个数组均沿着另一个维度进行广播

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

广播的规则：
规则1:如果两个数组的维度数不相同，那么小维度数组的形状将会在最左边补1。
规则2:如果两个数组的形状在任何一个维度上都不匹配，那么数组的形状会沿着维度
为 1 的维度扩展以匹配另外一个数组的形状。
规则3:如果两个数组的形状在任何一个维度上都不匹配并且没有任何一个维度等于1，那么会引发异常。

In [18]:
M = np.ones((2,3))
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
a = np.arange(3)
a

array([0, 1, 2])

In [20]:
a + M

array([[1., 2., 3.],
       [1., 2., 3.]])

In [21]:
a.shape

(3,)

In [22]:
M.shape

(2, 3)

In [24]:
a=np.arange(3).reshape((3,1))
print(a)
b=np.array()

array([[0],
       [1],
       [2]])

In [25]:
a.ndim

2

In [26]:
M.ndim

2